name: Trigger Jenkins Job

on:
  push:
    branches:
      - Jenkins

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        uses: appleboy/jenkins-action@v0.0.2
        with:
          url: 'https://specifies-trial-mexican-footwear.trycloudflare.com/'
          user: 'Mrunmayi'
          token: ${{ secrets.JENKINS_TOKEN }}
