name: Trigger Jenkins Build

on:
  push:
    branches:
      - Jenkins # Adjust to your branch

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' for Linux runner

    steps:
    - name: Trigger Jenkins Job
      env:
        INPUT_URL: 'http://localhost:8080'  # Jenkins URL
        INPUT_USER: ${{ secrets.JENKINS_USER }}  # Jenkins username
        INPUT_TOKEN: ${{ secrets.JENKINS_TOKEN }}  # Jenkins API token
        INPUT_JOB: 'github-test'  # Jenkins job name
