name: Check Jenkins Integration

on:
  push:
    branches: [ Jenkins ]  # Replace with your branch name(s)

jobs:
  check-jenkins:
    runs-on: ubuntu-latest

    steps:
    - name: Check Jenkins Availability
      run: |
        if ! curl -sSf -o /dev/null "${{ secrets.JENKINS_URL }}"; then
          echo "Jenkins server at ${{ secrets.JENKINS_URL }} is unreachable."
          exit 1
        fi
        echo "Jenkins server is reachable!"
