name: Trigger Jenkins Build

on:
  push:
    branches:
      - Jenkins  # Adjust to your branch name

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' for Linux runner

    steps:
    - name: ping Jenkins Server
      run: |
        ping http://localhost:8080


    - name: Trigger Jenkins Job
      env:
        JENKINS_URL: 'http://localhost:8080'  # Jenkins URL
        JENKINS_USER: ${{ secrets.JENKINS_USER }}  # Jenkins username
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}  # Jenkins API token
        JENKINS_JOB: 'github-test'  # Jenkins job name
      run: |
        curl -X POST -u "${JENKINS_USER}:${JENKINS_TOKEN}" "${JENKINS_URL}/job/${JENKINS_JOB}/build"
