name: Trigger Jenkins Build

on:
  push:
    branches:
      - Jenkins  # Adjust to your branch

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' for Linux runner

    steps:
    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@master
      with:
        url: 'http://localhost:8080/job/github-test/build'
        user: ${{ secrets.JENKINS_USER }}
        token: ${{ secrets.JENKINS_TOKEN }}
